name: Workflow Demo

on: [push]

jobs:
  job1:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a text file
        run: echo "Hello, world!" > hello.txt

      - name: Archive text file
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt

  job2: 
      needs: job1
      runs-on: ubuntu-latest

      steps: 
      - name: Download file from different job
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt

      - name: Display file content
        run: echo cat ./artifacts/hello.txt
