name: download

on: push

jobs:
  job1: 
    runs-on: ubuntu-latest

    steps: 
    - name: Download file from different job
      uses: actions/download-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt

    - name: Display file content
      run: echo cat ./artifacts/hello.txt
        

  
